"use client";

import { useState, useEffect, useMemo } from "react";
import { useRouter } from "next/navigation";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Loader2, Plus, Sparkles, Newspaper, ExternalLink } from "lucide-react";
import {
  HEADLINE_FEEDS,
  FEED_LABELS,
  type HeadlineItem,
} from "@/lib/headlines";
import {
  SLOTS_PER_WEEK,
  POST_COUNT_PRESETS,
  DEFAULT_POST_COUNT,
  nextMonday,
  formatWeekRange,
  parseISODate,
  toISODate,
} from "@/lib/week";

// How many weeks ahead the picker offers, starting at next Monday.
const WEEKS_AHEAD = 6;

// What each size means in practice, since "5 posts" alone doesn't say how
// they land across the week.
const POST_COUNT_HINTS: Record<number, string> = {
  5: "1 per weekday",
  10: "2 per weekday",
};

const PROGRESS_MESSAGES = [
  "Creating batch...",
  'Generating "AI Speak" posts...',
  'Generating "Tech Speak" posts...',
  'Generating "Quote Speak" posts...',
  'Generating "Cost Speak" posts...',
  'Generating "POTS Speak" posts...',
  'Generating "Personal Take" posts...',
  "Assigning schedules and images...",
  "Almost done...",
];

type BatchScope = "both" | "company" | "personal";

const SCOPE_OPTIONS: Array<{ value: BatchScope; label: string; hint: string }> = [
  { value: "both", label: "Both", hint: "Company page + Speck's profile" },
  { value: "company", label: "Company only", hint: "The five company categories" },
  { value: "personal", label: "Personal only", hint: "Personal Take posts only" },
];

// Test mode ignores the size picker: 2 per included category, capped at what
// a week can hold. "Both" wants 12 (six categories) but a week only has
// SLOTS_PER_WEEK slots, so it lands on 10.
const SCOPE_TEST_COUNTS: Record<BatchScope, number> = {
  both: Math.min(12, SLOTS_PER_WEEK),
  company: Math.min(10, SLOTS_PER_WEEK),
  personal: Math.min(2, SLOTS_PER_WEEK),
};

export function GenerateBatchModal() {
  const router = useRouter();

  // Batches are generated on a weekend for the week ahead, so next Monday is
  // the common case and needs no clicks.
  const weekOptions = useMemo(() => {
    const first = parseISODate(nextMonday());
    return Array.from({ length: WEEKS_AHEAD }, (_, i) =>
      toISODate(
        new Date(first.getFullYear(), first.getMonth(), first.getDate() + i * 7)
      )
    );
  }, []);

  const [open, setOpen] = useState(false);
  const [weekStart, setWeekStart] = useState(() => nextMonday());
  const [testMode, setTestMode] = useState(false);
  const [scope, setScope] = useState<BatchScope>("both");
  const [postCount, setPostCount] = useState(String(DEFAULT_POST_COUNT));
  // Defaults to off: images are generated by hand for now.
  const [includeImages, setIncludeImages] = useState(false);
  const [loading, setLoading] = useState(false);
  const [progressIndex, setProgressIndex] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [scanning, setScanning] = useState(false);
  const [scanId, setScanId] = useState<string | null>(null);
  const [headlines, setHeadlines] = useState<HeadlineItem[]>([]);
  // Nothing is used unless it is ticked — headlines are opt-in per item.
  const [pickedIds, setPickedIds] = useState<string[]>([]);
  const [scanError, setScanError] = useState<string | null>(null);
  // Free slots for the chosen week and scope. Read from the generate route so
  // this number and the one the POST enforces can never drift apart.
  const [slotsFree, setSlotsFree] = useState<number | null>(null);
  const [slotsError, setSlotsError] = useState<string | null>(null);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    setSlotsFree(null);
    setSlotsError(null);

    fetch(
      `/api/generate-batch?weekStart=${encodeURIComponent(weekStart)}&scope=${scope}`
    )
      .then(async (res) => {
        const data = await res.json();
        if (cancelled) return;
        if (!res.ok) throw new Error(data.error || "Could not read slots");
        setSlotsFree(data.slotsFree);
      })
      .catch((err) => {
        if (cancelled) return;
        setSlotsError(err instanceof Error ? err.message : "Could not read slots");
      });

    return () => {
      cancelled = true;
    };
  }, [open, weekStart, scope]);

  async function handleScanHeadlines() {
    setScanning(true);
    setScanError(null);
    try {
      const res = await fetch("/api/headlines/scan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ weekStart }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Scan failed");
      setHeadlines(data.items || []);
      setScanId(data.scanId || null);
      setPickedIds([]);
    } catch (err) {
      setScanError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setScanning(false);
    }
  }

  function togglePicked(id: string) {
    setPickedIds((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
    );
  }

  async function handleGenerate() {
    setLoading(true);
    setError(null);
    setProgressIndex(0);

    // Cycle through progress messages while waiting
    const interval = setInterval(() => {
      setProgressIndex((prev) =>
        prev < PROGRESS_MESSAGES.length - 1 ? prev + 1 : prev
      );
    }, 60000);

    try {
      // Persist the picks on the scan row before generating.
      if (scanId && pickedIds.length > 0) {
        await fetch("/api/headlines/scan", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ scanId, headlineIds: pickedIds }),
        }).catch(() => {});
      }

      const res = await fetch("/api/generate-batch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          weekStart,
          testMode,
          includeImages,
          scope,
          postCount: parseInt(postCount),
          scanId,
          headlineIds: pickedIds,
        }),
      });

      clearInterval(interval);

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Generation failed");
      }

      const data = await res.json();
      setOpen(false);
      router.push(`/batches/${data.batchId}`);
    } catch (err) {
      clearInterval(interval);
      setError(err instanceof Error ? err.message : "Something went wrong");
      setLoading(false);
    }
  }

  const chosenSize = parseInt(postCount) || DEFAULT_POST_COUNT;
  // The size is the exact post count for whichever scope is chosen — the
  // scope only decides which categories those posts are split across.
  const effectiveCount = testMode ? SCOPE_TEST_COUNTS[scope] : chosenSize;
  const scopeLabel = SCOPE_OPTIONS.find((o) => o.value === scope)!.label;

  // The route shortens a batch to what the week has free, so say the real
  // number here rather than promising posts that won't be generated.
  const willGenerate =
    slotsFree === null ? effectiveCount : Math.min(effectiveCount, slotsFree);
  const noSlots = slotsFree === 0;

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!loading || error) { setOpen(v); setLoading(false); setError(null); } }}>
      <DialogTrigger asChild>
        <Button
          size="lg"
          className="bg-blue-600 hover:bg-blue-700 text-white gap-2"
        >
          <Plus className="h-5 w-5" />
          Generate New Batch
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        {loading && !error ? (
          <div className="flex flex-col items-center py-10 gap-4">
            <Loader2 className="h-10 w-10 text-blue-600 animate-spin" />
            <div className="text-center">
              <p className="font-medium text-gray-900">
                {testMode
                  ? `Generating ${effectiveCount} test posts...`
                  : `Generating ${effectiveCount} posts...`}
              </p>
              <p className="text-sm text-gray-500 mt-1">
                {PROGRESS_MESSAGES[progressIndex]}
              </p>
              <p className="text-xs text-gray-400 mt-3">
                {testMode ? "This should take about 2 minutes" : "This can take up to 10 minutes"}
              </p>
            </div>
          </div>
        ) : (
          <>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-blue-600" />
                Generate New Batch
              </DialogTitle>
              <DialogDescription>
                {testMode
                  ? `Generate ${effectiveCount} test posts (2 per category, ${scopeLabel.toLowerCase()}) to review content quality and image templates before committing to a full batch.`
                  : `Generate ${willGenerate} AI-written posts (${scopeLabel.toLowerCase()}) for ${formatWeekRange(weekStart)}, spread evenly Monday to Friday. You can review and edit them before approving.`}
              </DialogDescription>
            </DialogHeader>

            <div className="grid gap-4 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="weekStart">Week</Label>
                  <Select value={weekStart} onValueChange={setWeekStart}>
                    <SelectTrigger id="weekStart">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {weekOptions.map((monday, i) => (
                        <SelectItem key={monday} value={monday}>
                          {formatWeekRange(monday)}
                          {i === 0 ? " · next week" : ""}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <p className="text-xs text-gray-400">
                    {slotsError ? (
                      <span className="text-red-600">{slotsError}</span>
                    ) : slotsFree === null ? (
                      "Checking slots…"
                    ) : (
                      <>
                        {slotsFree} of {SLOTS_PER_WEEK} slots free for{" "}
                        {scopeLabel}.
                        {noSlots
                          ? " Delete a batch in that week or pick another."
                          : ""}
                      </>
                    )}
                  </p>
                </div>
              </div>

              {/* Headlines — optional. Scanned on demand, and only the items
                  ticked here reach the prompt. */}
              <div className="space-y-2 rounded-lg border p-3">
                <div className="flex items-center justify-between gap-2">
                  <Label className="text-sm font-medium">Headlines</Label>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={handleScanHeadlines}
                    disabled={scanning}
                  >
                    {scanning ? (
                      <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
                    ) : (
                      <Newspaper className="h-4 w-4 mr-1.5 text-blue-600" />
                    )}
                    {scanning
                      ? "Scanning…"
                      : headlines.length > 0
                      ? "Rescan"
                      : "Scan headlines"}
                  </Button>
                </div>

                {scanError && (
                  <p className="text-xs text-red-600">{scanError}</p>
                )}

                {headlines.length === 0 ? (
                  <p className="text-xs text-gray-400">
                    Optional. Finds recent crypto, AI/tech, and AI-in-voice
                    stories so posts can reference real events instead of
                    inventing them. Nothing is used unless you tick it.
                  </p>
                ) : (
                  <div className="space-y-3 max-h-56 overflow-y-auto pr-1">
                    {HEADLINE_FEEDS.filter((feed) =>
                      headlines.some((h) => h.feed === feed)
                    ).map((feed) => (
                      <div key={feed} className="space-y-1.5">
                        <p className="text-xs font-medium uppercase text-gray-400">
                          {FEED_LABELS[feed]}
                        </p>
                        {headlines
                          .filter((h) => h.feed === feed)
                          .map((item) => (
                            <div key={item.id} className="flex gap-2">
                              <Checkbox
                                id={`headline-${item.id}`}
                                checked={pickedIds.includes(item.id)}
                                onCheckedChange={() => togglePicked(item.id)}
                                className="mt-0.5"
                              />
                              <Label
                                htmlFor={`headline-${item.id}`}
                                className="text-xs font-normal cursor-pointer leading-snug"
                              >
                                {item.headline}
                                <span className="block text-gray-400">
                                  {item.source_name || "Unknown source"}
                                  {item.published_date
                                    ? ` · ${item.published_date}`
                                    : ""}
                                  {item.source_url && (
                                    <a
                                      href={item.source_url}
                                      target="_blank"
                                      rel="noopener noreferrer"
                                      onClick={(e) => e.stopPropagation()}
                                      className="ml-1 inline-flex items-center text-blue-600 hover:underline"
                                    >
                                      <ExternalLink className="h-3 w-3" />
                                    </a>
                                  )}
                                </span>
                              </Label>
                            </div>
                          ))}
                      </div>
                    ))}
                    <p className="text-xs text-gray-400 pt-1">
                      {pickedIds.length} picked. Used by AI, Tech, POTS, and
                      Personal Take only.
                    </p>
                  </div>
                )}
              </div>

              {/* Batch size. Test mode ignores it, so it's hidden there. */}
              {!testMode && (
                <div className="space-y-2">
                  <Label htmlFor="postCount">Posts</Label>
                  <Select value={postCount} onValueChange={setPostCount}>
                    <SelectTrigger id="postCount">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {POST_COUNT_PRESETS.map((n) => (
                        <SelectItem key={n} value={String(n)}>
                          {n} posts
                          {POST_COUNT_HINTS[n] ? ` · ${POST_COUNT_HINTS[n]}` : ""}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <p className="text-xs text-gray-400">
                    Spread evenly Monday to Friday. This is the exact count for
                    whichever scope you pick.
                  </p>
                </div>
              )}

              {/* Scope — a radio group built from buttons so it needs no new
                  dependency. role/aria-checked keep it a real radio group. */}
              <div className="space-y-2">
                <Label>Scope</Label>
                <div role="radiogroup" aria-label="Batch scope" className="grid gap-1.5">
                  {SCOPE_OPTIONS.map((option) => {
                    const selected = scope === option.value;
                    return (
                      <button
                        key={option.value}
                        type="button"
                        role="radio"
                        aria-checked={selected}
                        onClick={() => setScope(option.value)}
                        className={`flex items-start gap-2.5 rounded-lg border p-2.5 text-left transition-colors ${
                          selected
                            ? "border-blue-600 bg-blue-50"
                            : "border-gray-200 hover:bg-gray-50"
                        }`}
                      >
                        <span
                          className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full border ${
                            selected ? "border-blue-600" : "border-gray-300"
                          }`}
                        >
                          {selected && (
                            <span className="h-2 w-2 rounded-full bg-blue-600" />
                          )}
                        </span>
                        <span className="min-w-0">
                          <span className="block text-sm font-medium text-gray-900">
                            {option.label}
                          </span>
                          <span className="block text-xs text-gray-500">
                            {option.hint} &middot;{" "}
                            {testMode
                              ? SCOPE_TEST_COUNTS[option.value]
                              : chosenSize}{" "}
                            posts
                          </span>
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="testMode"
                  checked={testMode}
                  onCheckedChange={(checked) => setTestMode(checked === true)}
                />
                <Label htmlFor="testMode" className="text-sm font-normal cursor-pointer">
                  Test mode ({effectiveCount} posts — 2 per category, faster generation)
                </Label>
              </div>

              <div className="rounded-lg border p-3 space-y-1">
                <div className="flex items-center justify-between">
                  <Label htmlFor="includeImages" className="text-sm font-medium cursor-pointer">
                    Include images
                  </Label>
                  <Switch
                    id="includeImages"
                    checked={includeImages}
                    onCheckedChange={setIncludeImages}
                  />
                </div>
                <p className="text-xs text-gray-500">
                  {includeImages
                    ? "Images will be generated for eligible post categories"
                    : "Posts will be text-only — no images generated"}
                </p>
              </div>

              {error && (
                <p className="text-sm text-red-600 bg-red-50 rounded-md p-3">
                  {error}
                </p>
              )}

              <Button
                onClick={handleGenerate}
                disabled={noSlots}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white"
              >
                {noSlots
                  ? "No slots free this week"
                  : testMode
                  ? `Generate ${willGenerate} Test Posts`
                  : `Generate ${willGenerate} Posts`}
              </Button>
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
